[build]
  publish = "."

[[headers]]
  for = "/service-worker.js"

  [headers.values]
    Cache-Control = "no-cache"

[[headers]]
  for = "/*"

  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
